project:
  type: website
  output-dir: _site

website:
  title: "AFW 360 At A Glance"
  navbar:
    title: false
  page-footer:
    left: "© 2026 World Bank Group"
    right: "AFW 360 Pilot Dashboard"

format:
  html:
    theme: cosmo
    toc: false
    code-fold: true
    grid:
      margin-width: 0px
