<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-29">

<title>FMR guide: local Fusion Metadata Registry for the AFW 360 standard – AFW360 - Platform Concept</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0155b9a915285bfaf60828b10cd98adb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">AFW360 - Platform Concept</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./data-standard.html" aria-current="page"> 
<span class="menu-text">Standard</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tools.html"> 
<span class="menu-text">Dashboards and tools</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/wbEAWPV/AFW360_Glance"> <i class="bi bi-github" role="img" aria-label="Source repository on GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./data-standard.html">AFW360 SDMX Standard</a></li><li class="breadcrumb-item"><a href="./sdmx-conformance.html">Technical documentation</a></li><li class="breadcrumb-item"><a href="./fmr-guide.html">FMR guide</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./data-standard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AFW360 SDMX Standard</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Technical documentation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sdmx-conformance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SDMX conformance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./transition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Transition record</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./input-tables-findings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Input tables findings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fmr-guide.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">FMR guide</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-is-installed" id="toc-what-is-installed" class="nav-link active" data-scroll-target="#what-is-installed">What is installed</a></li>
  <li><a href="#install-steps-as-run" id="toc-install-steps-as-run" class="nav-link" data-scroll-target="#install-steps-as-run">Install steps (as run)</a></li>
  <li><a href="#start-and-stop" id="toc-start-and-stop" class="nav-link" data-scroll-target="#start-and-stop">Start and stop</a></li>
  <li><a href="#workflow" id="toc-workflow" class="nav-link" data-scroll-target="#workflow">Workflow</a>
  <ul class="collapse">
  <li><a href="#generate-the-sdmx-files" id="toc-generate-the-sdmx-files" class="nav-link" data-scroll-target="#generate-the-sdmx-files">1. Generate the SDMX files</a></li>
  <li><a href="#load-the-structures" id="toc-load-the-structures" class="nav-link" data-scroll-target="#load-the-structures">2. Load the structures</a></li>
  <li><a href="#validate-the-data" id="toc-validate-the-data" class="nav-link" data-scroll-target="#validate-the-data">3. Validate the data</a></li>
  <li><a href="#export-and-round-trip" id="toc-export-and-round-trip" class="nav-link" data-scroll-target="#export-and-round-trip">4. Export and round trip</a></li>
  <li><a href="#edit-structures-in-fmr" id="toc-edit-structures-in-fmr" class="nav-link" data-scroll-target="#edit-structures-in-fmr">5. Edit structures in FMR</a></li>
  <li><a href="#validation-only-use" id="toc-validation-only-use" class="nav-link" data-scroll-target="#validation-only-use">6. Validation-only use</a></li>
  </ul></li>
  <li><a href="#findings-from-the-install" id="toc-findings-from-the-install" class="nav-link" data-scroll-target="#findings-from-the-install">Findings from the install</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./data-standard.html">AFW360 SDMX Standard</a></li><li class="breadcrumb-item"><a href="./sdmx-conformance.html">Technical documentation</a></li><li class="breadcrumb-item"><a href="./fmr-guide.html">FMR guide</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">FMR guide: local Fusion Metadata Registry for the AFW 360 standard</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This guide records the real steps used on 2026-09-29 (work package WP8b) to run the Fusion Metadata Registry (FMR) locally on Windows 11 without administrator rights or Docker, and the workflow for loading, validating and editing the AFW 360 structures. The research behind it, with sources, is in <code>tools/fmr/README.md</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Status: load, validation and round trip work through the SDMX-ML 3.0 profile
</div>
</div>
<div class="callout-body-container callout-body">
<p>FMR 12.4.2 does not read SDMX-ML 3.1, so <code>tools/fmr/fmr_load.R</code> loads the SDMX-ML 3.0 profile that <code>pipeline/build_sdmx.R --sdmx-ml-version 3.0</code> writes to <code>tmp/fmr/v30/</code> (same artefacts, <code>v3_0</code> namespaces, without the metadata structure, metadataflow and metadata provision agreement). The 3.1 file under <code>sdmx/</code> stays the canonical committed output. The data files in <code>data/</code> (SDMX-CSV 2.1) validate without change, and the structures exported back from FMR (SDMX-ML 3.0) give an empty <code>pipeline/import_sdmx.R --diff</code>. See <a href="#workflow">Workflow</a>.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Why the 3.0 profile: FMR 12.4.2 rejects the SDMX-ML 3.1 structure message
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Loading <code>sdmx/structures/AFW360_structures.xml</code> (SDMX-ML 3.1, <code>v3_1</code> namespaces) fails. Response of <code>POST /ws/secure/sdmxapi/rest/</code>, both as a multipart upload (<code>-F uploadFile=@...</code>) and as a raw <code>application/xml</code> body:</p>
<pre><code>HTTP 400
&lt;message:Error xmlns:message="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message" ...&gt;
  &lt;message:ErrorMessage code="150"&gt;
    &lt;com:Text&gt;Unrecognised file format, contents of file are: &lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;mes:Structure xmlns:mes="http://www.sdmx.org/resources/sdmxml/schemas/v3_1/message" xmlns:str="http://www.sdmx.org/resources/sdmxml/schemas/v3_1/structure" ...</code></pre>
<p>FMR log (<code>tools/fmr/runtime/tomcat/logs/FusionRegistryWarnings.log</code>):</p>
<pre><code>ERROR http-nio-8080-exec-7 io.sdmx.format.ml.engine.error.ErrorWriterEngineV21 - Unrecognised file format, contents of file are: &lt;?xml version="1.0" encoding="UTF-8"?&gt;</code></pre>
<p>FMR’s documentation lists SDMX-ML up to 3.0; the 3.1 namespaces are not recognised at all (the error body itself is SDMX-ML 2.1). Following the plan’s contingency (section 2.13), WP8b2 added the <code>--sdmx-ml-version 3.0</code> option to <code>pipeline/build_sdmx.R</code>. With the 3.0 profile the format error is gone and the only remaining obstacle was the agency <code>WB</code> (see step 2 of the workflow).</p>
</div>
</div>
</div>
<section id="what-is-installed" class="level2">
<h2 class="anchored" data-anchor-id="what-is-installed">What is installed</h2>
<p>Everything lives under <code>tools/fmr/runtime/</code> (gitignored); nothing is written to the registry, services or the user profile.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Version</th>
<th>Location</th>
<th>Port</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Java</td>
<td>Azul Zulu 21.0.12.1 (already on <code>PATH</code>, <code>JAVA_HOME</code>)</td>
<td><code>C:\Program Files\Zulu\zulu-21</code></td>
<td></td>
</tr>
<tr class="even">
<td>Apache Tomcat</td>
<td>10.1.60 (Windows zip)</td>
<td><code>tools/fmr/runtime/tomcat</code></td>
<td>8080 (HTTP), 8015 (shutdown)</td>
</tr>
<tr class="odd">
<td>FMR</td>
<td>12.4.2 (<code>fmr-12.4.2.war</code>, 129,151,617 bytes)</td>
<td><code>tools/fmr/runtime/tomcat/webapps/ROOT.war</code></td>
<td>served at <code>/</code></td>
</tr>
<tr class="even">
<td>MySQL</td>
<td>8.0.46 (noinstall zip, MD5 checked)</td>
<td><code>tools/fmr/runtime/mysql</code>, data in <code>mysql/data</code></td>
<td>3306, <code>127.0.0.1</code> only</td>
</tr>
<tr class="odd">
<td>MySQL Connector/J</td>
<td>9.6.0</td>
<td><code>tools/fmr/runtime/tomcat/lib/mysql-connector-j-9.6.0.jar</code></td>
<td></td>
</tr>
</tbody>
</table>
<ul>
<li>Downloads are kept in <code>tools/fmr/runtime/dl/</code>, logs of the two processes in <code>tools/fmr/runtime/logs/</code>, Tomcat and FMR logs in <code>tools/fmr/runtime/tomcat/logs/</code> (<code>FusionRegistry.log</code>, <code>FusionRegistryWarnings.log</code>).</li>
<li>Java heap: <code>-Xmx16g</code> (the FMR wiki’s value; the machine has 128 GB).</li>
<li>Database <code>fmr</code> (utf8mb4), user <code>fmruser@localhost</code>. MySQL <code>root</code> has no password and listens on <code>127.0.0.1</code> only.</li>
<li>FMR superuser: <code>root</code>. Passwords (database user and FMR superuser) are in <code>tools/fmr/runtime/secrets.txt</code>, never committed.</li>
<li>FMR’s home folder and <code>fmr.properties</code> are in <code>tools/fmr/runtime/home/</code> (set through <code>-Duser.home</code> and <code>-DRegistryProperties</code>).</li>
</ul>
</section>
<section id="install-steps-as-run" class="level2">
<h2 class="anchored" data-anchor-id="install-steps-as-run">Install steps (as run)</h2>
<p>Commands run from the repository root; Git Bash unless marked PowerShell.</p>
<ol type="1">
<li><p>Check resources: free disk space, RAM and ports (<code>netstat -ano | findstr LISTENING</code>). Port 8005, Tomcat’s default shutdown port, was taken by a system process, so the shutdown port is 8015.</p></li>
<li><p>Download into <code>tools/fmr/runtime/dl/</code> (curl needs <code>--ssl-no-revoke</code> on this machine):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">--ssl-no-revoke</span> <span class="at">-sSLO</span> https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.60/bin/apache-tomcat-10.1.60.zip</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">--ssl-no-revoke</span> <span class="at">-sSLO</span> https://github.com/bis-med-it/fmr-public/releases/download/v12.4.2/fmr-12.4.2.war</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">--ssl-no-revoke</span> <span class="at">-sSLO</span> https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.46-winx64.zip</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">--ssl-no-revoke</span> <span class="at">-sSLO</span> https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-9.6.0.zip</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Check the Tomcat zip against its <code>.sha512</code> file on <code>downloads.apache.org</code>, the WAR size against the GitHub release (129,151,617 bytes), and the MySQL zip’s MD5 against the MySQL download page.</p></li>
<li><p>Unzip (PowerShell <code>Expand-Archive</code>) to <code>tools/fmr/runtime/tomcat</code> and <code>tools/fmr/runtime/mysql</code>; copy the Connector/J jar to <code>tools/fmr/runtime/tomcat/lib/</code> (Tomcat’s own <code>lib</code>, because the database connection is a Tomcat JNDI resource).</p></li>
<li><p>MySQL: write <code>tools/fmr/runtime/mysql/my.ini</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode ini code-with-copy"><code class="sourceCode ini"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">[mysqld]</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="dt">basedir</span><span class="ot">=</span><span class="st">&lt;repo&gt;/tools/fmr/runtime/mysql</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="dt">datadir</span><span class="ot">=</span><span class="st">&lt;repo&gt;/tools/fmr/runtime/mysql/data</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="dt">port</span><span class="ot">=</span><span class="dv">3306</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="dt">bind-address</span><span class="ot">=</span><span class="st">127.0.0.1</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="dt">mysqlx</span><span class="ot">=</span><span class="kw">OFF</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="dt">log-error</span><span class="ot">=</span><span class="st">&lt;repo&gt;/tools/fmr/runtime/logs/mysqld.err</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="kw">[client]</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="dt">port</span><span class="ot">=</span><span class="dv">3306</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="dt">host</span><span class="ot">=</span><span class="st">127.0.0.1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>then initialise the data directory, start the server (see below) and create the database:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ex">tools/fmr/runtime/mysql/bin/mysqld</span> <span class="at">--defaults-file</span><span class="op">=</span>tools/fmr/runtime/mysql/my.ini <span class="at">--initialize-insecure</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="ex">tools/fmr/runtime/mysql/bin/mysql</span> <span class="at">--defaults-file</span><span class="op">=</span>tools/fmr/runtime/mysql/my.ini <span class="at">-u</span> root <span class="at">-e</span> <span class="dt">\</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CREATE DATABASE fmr CHARACTER SET utf8mb4;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="st">   CREATE USER 'fmruser'@'localhost' IDENTIFIED BY '&lt;password&gt;';</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="st">   GRANT ALL ON fmr.* TO 'fmruser'@'localhost'; FLUSH PRIVILEGES;"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>Tomcat configuration:</p>
<ul>
<li><p><code>conf/server.xml</code>: <code>&lt;Server port="8015" shutdown="SHUTDOWN"&gt;</code>.</p></li>
<li><p><code>conf/context.xml</code>: add, inside <code>&lt;Context&gt;</code>, the JNDI resource from the FMR wiki’s Jndi page:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode xml code-with-copy"><code class="sourceCode xml"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>&lt;<span class="kw">Resource</span> <span class="ot">name=</span><span class="st">"fmrdatabase"</span> <span class="ot">auth=</span><span class="st">"Container"</span> <span class="ot">type=</span><span class="st">"javax.sql.DataSource"</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="ot">driverClassName=</span><span class="st">"com.mysql.cj.jdbc.Driver"</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="ot">url=</span><span class="st">"jdbc:mysql://127.0.0.1:3306/fmr?allowPublicKeyRetrieval=true</span><span class="dv">&amp;amp;</span><span class="st">useSSL=false"</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="ot">username=</span><span class="st">"fmruser"</span> <span class="ot">password=</span><span class="st">"</span><span class="er">&lt;</span><span class="st">password&gt;"</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="ot">maxTotal=</span><span class="st">"10"</span> <span class="ot">minIdle=</span><span class="st">"5"</span> <span class="ot">maxWaitMillis=</span><span class="st">"-1"</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="ot">timeBetweenEvictionRunsMillis=</span><span class="st">"7200000"</span> <span class="ot">minEvictableIdleTimeMillis=</span><span class="st">"3600000"</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="ot">defaultAutoCommit=</span><span class="st">"false"</span> /&gt;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p><code>bin/setenv.bat</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode bat code-with-copy"><code class="sourceCode dosbat"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">set</span> <span class="st">"</span><span class="va">JAVA_OPTS</span>=<span class="pp">%</span><span class="va">JAVA_OPTS</span><span class="pp">%</span><span class="st"> -Xmx16g -Duser.home=&lt;repo&gt;/tools/fmr/runtime/home -DRegistryProperties=file:///&lt;repo&gt;/tools/fmr/runtime/home/fmr.properties"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>Copy <code>fmr-12.4.2.war</code> to <code>webapps/ROOT.war</code> and delete the default <code>webapps/ROOT</code> folder, so FMR is served at <code>http://localhost:8080/</code>.</p></li>
</ul></li>
<li><p>Start Tomcat (see below). The first start takes about two minutes while the WAR unpacks; <code>http://localhost:8080/</code> then redirects to <code>/install.html</code>.</p></li>
<li><p>First-run setup. In a browser: open <code>http://localhost:8080/</code>, accept the licence, choose <em>JNDI connection</em> with JNDI name <code>fmrdatabase</code>, context <code>java:/comp/env</code>, driver <code>com.mysql.cj.jdbc.Driver</code>, server URL <code>http://localhost:8080</code>, superuser <code>root</code> and a password. The same steps without a browser (the calls the setup page makes; a session cookie from <code>install.html</code> is required, otherwise the calls return 401):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="va">B</span><span class="op">=</span>http://localhost:8080/ws/secure/settings</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="va">C</span><span class="op">=</span><span class="st">"-s -c tmp/fmr/cj -b tmp/fmr/cj -H Content-Type:application/json"</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="va">$C</span> <span class="at">-o</span> /dev/null http://localhost:8080/install.html</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="va">$C</span> <span class="at">-X</span> POST <span class="va">$B</span>/saveLicenceAgreement</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="va">$C</span> <span class="at">-d</span> <span class="st">'{"jndiName":"fmrdatabase","jndiContext":"java:/comp/env","driver":"com.mysql.cj.jdbc.Driver"}'</span> <span class="va">$B</span>/saveDatabaseSettings</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="va">$C</span> <span class="at">-d</span> <span class="st">'http://localhost:8080'</span> <span class="va">$B</span>/saveServerUrl</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="va">$C</span> <span class="at">-d</span> <span class="st">'Fusion Metadata Registry'</span> <span class="va">$B</span>/saveRegistryName</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="va">$C</span> <span class="at">-d</span> <span class="st">'{"username":"root","password":"&lt;password&gt;","maxLoginAttempts":"-1"}'</span> <span class="va">$B</span>/saveRootSecuritySettings</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="va">$C</span> <span class="at">-X</span> POST <span class="va">$B</span>/completeInstall</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Each call returns <code>{"Success":[true]}</code>. Afterwards <code>http://localhost:8080/</code> returns 200 and the <code>fmr</code> database holds 34 tables.</p></li>
</ol>
</section>
<section id="start-and-stop" class="level2">
<h2 class="anchored" data-anchor-id="start-and-stop">Start and stop</h2>
<p>Start MySQL, then Tomcat (PowerShell, from anywhere; both run hidden as the current user, output in <code>tools/fmr/runtime/logs/</code>):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="va">$r</span> <span class="op">=</span> <span class="st">"C:\Users\wb532966\eb-local\AFW360_Glance\tools\fmr\runtime"</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Start-Process</span> <span class="op">-</span>FilePath <span class="st">"</span><span class="va">$r</span><span class="st">\mysql\bin\mysqld.exe"</span> <span class="op">-</span>ArgumentList <span class="st">"--defaults-file=</span><span class="ch">`"</span><span class="va">$r</span><span class="st">\mysql\my.ini</span><span class="ch">`"</span><span class="st">"</span> <span class="op">-</span>RedirectStandardOutput <span class="st">"</span><span class="va">$r</span><span class="st">\logs\mysqld.out"</span> <span class="op">-</span>RedirectStandardError <span class="st">"</span><span class="va">$r</span><span class="st">\logs\mysqld.stderr"</span> <span class="op">-</span>WindowStyle Hidden</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="va">$env</span><span class="op">:</span><span class="va">CATALINA_HOME</span> <span class="op">=</span> <span class="st">"</span><span class="va">$r</span><span class="st">\tomcat"</span><span class="op">;</span> <span class="va">$env</span><span class="op">:</span><span class="va">CATALINA_BASE</span> <span class="op">=</span> <span class="st">"</span><span class="va">$r</span><span class="st">\tomcat"</span><span class="op">;</span> <span class="va">$env</span><span class="op">:</span><span class="va">JAVA_HOME</span> <span class="op">=</span> <span class="st">"C:\Program Files\Zulu\zulu-21"</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">Start-Process</span> <span class="op">-</span>FilePath <span class="st">"</span><span class="va">$r</span><span class="st">\tomcat\bin\catalina.bat"</span> <span class="op">-</span>ArgumentList <span class="st">"run"</span> <span class="op">-</span>WorkingDirectory <span class="st">"</span><span class="va">$r</span><span class="st">\tomcat"</span> <span class="op">-</span>RedirectStandardOutput <span class="st">"</span><span class="va">$r</span><span class="st">\logs\tomcat.out"</span> <span class="op">-</span>RedirectStandardError <span class="st">"</span><span class="va">$r</span><span class="st">\logs\tomcat.err"</span> <span class="op">-</span>WindowStyle Hidden</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Ready when <code>curl -s -o /dev/null -w "%{http_code}\n" http://localhost:8080/</code> prints 200 (about two minutes).</p>
<p>Stop Tomcat, then MySQL:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="va">$r</span> <span class="op">=</span> <span class="st">"C:\Users\wb532966\eb-local\AFW360_Glance\tools\fmr\runtime"</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="va">$env</span><span class="op">:</span><span class="va">CATALINA_HOME</span> <span class="op">=</span> <span class="st">"</span><span class="va">$r</span><span class="st">\tomcat"</span><span class="op">;</span> <span class="va">$env</span><span class="op">:</span><span class="va">CATALINA_BASE</span> <span class="op">=</span> <span class="st">"</span><span class="va">$r</span><span class="st">\tomcat"</span><span class="op">;</span> <span class="va">$env</span><span class="op">:</span><span class="va">JAVA_HOME</span> <span class="op">=</span> <span class="st">"C:\Program Files\Zulu\zulu-21"</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="op">&amp;</span> <span class="st">"</span><span class="va">$r</span><span class="st">\tomcat\bin\shutdown.bat"</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="op">&amp;</span> <span class="st">"</span><span class="va">$r</span><span class="st">\mysql\bin\mysqladmin.exe"</span> <span class="st">"--defaults-file=</span><span class="va">$r</span><span class="st">\mysql\my.ini"</span> <span class="op">-</span>u root shutdown</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="workflow" class="level2">
<h2 class="anchored" data-anchor-id="workflow">Workflow</h2>
<p>All commands run from the repository root in Git Bash, with FMR started (see <a href="#start-and-stop">Start and stop</a>). The scripts use the R packages <code>curl</code> and <code>jsonlite</code>. The FMR address comes from <code>FMR_BASE</code> (default <code>http://localhost:8080</code>); the account used to load structures comes from <code>FMR_USER</code> and <code>FMR_PASSWORD</code>, or else from <code>tools/fmr/runtime/secrets.txt</code> (<code>FMR_ADMIN_USER</code>, <code>FMR_ADMIN_PASSWORD</code>). Every response is kept under <code>tmp/fmr/</code>.</p>
<section id="generate-the-sdmx-files" class="level3">
<h3 class="anchored" data-anchor-id="generate-the-sdmx-files">1. Generate the SDMX files</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> pipeline/build_sdmx.R <span class="at">--root</span> .</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This writes the canonical SDMX-ML 3.1 message under <code>sdmx/</code>. It is not what FMR loads (see the status box); step 2 builds the 3.0 profile itself.</p>
</section>
<section id="load-the-structures" class="level3">
<h3 class="anchored" data-anchor-id="load-the-structures">2. Load the structures</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> tools/fmr/fmr_load.R <span class="at">--root</span> .</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The script runs four steps:</p>
<ol type="1">
<li><p><strong>FMR up?</strong> <code>GET &lt;FMR_BASE&gt;/</code> must return 200.</p></li>
<li><p><strong>Register the agency <code>WB</code>, once.</strong> The structure message declares the sub-agency <code>WB.AFW360</code> in the agency scheme <code>WB:AGENCIES(1.0)</code>. FMR can only store that scheme when the top-level agency <code>WB</code> exists in its own scheme <code>SDMX:AGENCIES(1.0)</code>; otherwise the load fails with</p>
<pre><code>HTTP 404, error code 100: Could not resolve reference from structure
Agency Scheme 'WB:AGENCIES(1.0)' to structure Agency
'urn:sdmx:org.sdmx.infomodel.base.Agency=SDMX:AGENCIES(1.0).WB'</code></pre>
<p>The script reads <code>GET /sdmx/v2/structure/agencyscheme/SDMX/AGENCIES/1.0</code> and, only when <code>WB</code> is missing, submits <code>tools/fmr/agencies_bootstrap.xml</code> (a SDMX-ML 3.0 message holding <code>SDMX:AGENCIES(1.0)</code> with the items <code>SDMX</code> and <code>WB</code>) to the same endpoint as step 4. The FMR superuser account from the install has the rights for this; no UI step is needed. On a fresh FMR the scheme holds only <code>SDMX</code>, which the bootstrap keeps. Response saved to <code>tmp/fmr/agencies_response.xml</code>. In the web interface the same is done under <em>Agencies</em> by adding <code>WB</code> to the top-level scheme.</p></li>
<li><p><strong>Build the SDMX-ML 3.0 profile:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> pipeline/build_sdmx.R <span class="at">--root</span> . <span class="at">--sdmx-ml-version</span> 3.0 <span class="at">--out-root</span> tmp/fmr/v30</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>writes <code>tmp/fmr/v30/sdmx/structures/AFW360_structures.xml</code>: the 22 codelists, concept scheme, data structure, dataflow, provision agreement and agency and provider schemes with <code>v3_0</code> namespaces; no metadata structure, metadataflow or metadata provision agreement (their 3.0 XML differs).</p></li>
<li><p><strong>Load it:</strong> <code>POST /ws/secure/sdmxapi/rest/</code> with the file as the <code>application/xml</code> body, header <code>ACTION: REPLACE</code> (option <code>--action</code>) and HTTP Basic authentication. The response is saved to <code>tmp/fmr/load_response.xml</code>. The script exits 0 on HTTP 200 and prints <code>Success</code> when FMR reports stored structures. A repeated load of an unchanged message returns HTTP 200 with an empty <code>SubmitStructureResponse</code> (nothing to replace), printed as <code>HTTP 200</code>.</p></li>
</ol>
<p><code>Rscript tools/fmr/fmr_load.R --root . --file &lt;message.xml&gt;</code> skips steps 2 and 3 and loads the given message. The same load is possible in the web interface (<em>Load Structures</em>), with the 3.0 profile.</p>
</section>
<section id="validate-the-data" class="level3">
<h3 class="anchored" data-anchor-id="validate-the-data">3. Validate the data</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> tools/fmr/fmr_validate.R <span class="at">--root</span> .</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Each <code>data/AFW360_HH_*_SURVEY.csv</code> is POSTed unchanged to <code>POST /ws/public/data/validate</code> (no login needed) with <code>Content-Type: application/vnd.sdmx.data+csv;version=2.1.0</code>. FMR answers with a JSON report, saved as <code>tmp/fmr/&lt;ISO3&gt;_&lt;YEAR&gt;_SURVEY_validation.json</code>. The script prints one line per file and exits 0 only when every report says <code>"Errors": false</code> and lists no error entries. Result on 2026-09-29:</p>
<pre><code>AFW360_HH_GNB_2021_SURVEY.csv: HTTP 200, format SDMX CSV v2.0, dataflow WB.AFW360:AFW360_HH(0.3.0), 2268 observations, Errors: false, error entries: 0
AFW360_HH_SEN_2021_SURVEY.csv: HTTP 200, format SDMX CSV v2.0, dataflow WB.AFW360:AFW360_HH(0.3.0), 3003 observations, Errors: false, error entries: 0</code></pre>
<p>FMR reads the SDMX-CSV 2.1 files as it reads SDMX-CSV 2.0 (the report’s <code>FileFormat</code> says <code>SDMX CSV v2.0</code>): the header <code>STRUCTURE,STRUCTURE_ID,ACTION,...</code> is the same in both versions and the files use no 2.1-only feature. The data files need no change.</p>
</section>
<section id="export-and-round-trip" class="level3">
<h3 class="anchored" data-anchor-id="export-and-round-trip">4. Export and round trip</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> tools/fmr/fmr_export.R <span class="at">--root</span> . <span class="at">--out</span> tmp/fmr/export.xml</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> pipeline/import_sdmx.R <span class="at">--root</span> . <span class="at">--diff</span> tmp/fmr/export.xml</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>fmr_export.R</code> GETs <code>/sdmx/v2/structure/*/WB,WB.AFW360/*/*?detail=full</code>, every artefact maintained by <code>WB</code> (the scheme <code>WB:AGENCIES</code>) or <code>WB.AFW360</code>. It asks for SDMX-ML 3.1 first; FMR 12.4.2 answers HTTP 406, so the script takes SDMX-ML 3.0 (<code>v3_0</code> namespaces), which <code>import_sdmx.R</code> reads. With the structures loaded as in step 2, the diff prints nothing on standard output: FMR returns every code, name, description and annotation that the CSVs under <code>metadata/</code> hold. <code>import_sdmx.R</code> notes on standard error that <code>CL_FIGURE</code>, <code>CL_SOURCE</code> and <code>CL_SURVEY</code> are derived from registries and are reported, not written; that is expected. What does not travel: the metadata structure, metadataflow and metadata provision agreement (not in the 3.0 profile, so not in FMR), and the message header (FMR writes its own ID and sender).</p>
</section>
<section id="edit-structures-in-fmr" class="level3">
<h3 class="anchored" data-anchor-id="edit-structures-in-fmr">5. Edit structures in FMR</h3>
<p>In FMR, work on a copy versioned <code>&lt;next&gt;-draft</code>; export it (step 4); run <code>Rscript pipeline/import_sdmx.R --root . --diff &lt;export.xml&gt;</code> to see the changes against the CSVs, then <code>--apply</code>; commit through a pull request; at release, bump <code>metadata/VERSION</code>, regenerate (step 1) and reload (step 2).</p>
</section>
<section id="validation-only-use" class="level3">
<h3 class="anchored" data-anchor-id="validation-only-use">6. Validation-only use</h3>
<p>Steps 1 to 3.</p>
</section>
</section>
<section id="findings-from-the-install" class="level2">
<h2 class="anchored" data-anchor-id="findings-from-the-install">Findings from the install</h2>
<ul>
<li>FMR 12.4.2 runs on Azul Zulu 21 (not named as tested by the vendor) and Tomcat 10.1.60 with MySQL 8.0.46 and Connector/J 9.6.0.</li>
<li>FMR rejects SDMX-ML 3.1 structure messages (error 150, status box) and does not offer 3.1 on export (HTTP 406); it loads and exports SDMX-ML 3.0.</li>
<li>FMR needs the top-level agency <code>WB</code> in <code>SDMX:AGENCIES(1.0)</code> before any <code>WB.AFW360</code> structure loads; <code>fmr_load.R</code> registers it when missing.</li>
<li>FMR accepts the SDMX-CSV 2.1 data files as they are and reports them as SDMX-CSV 2.0.</li>
<li>FMR’s error and submission responses are SDMX-ML 2.1 documents, whatever the version of the message sent.</li>
<li>FMR’s default home folder is <code>&lt;user home&gt;\SDMX_IO\FMR</code>; with <code>-Duser.home</code> and <code>-DRegistryProperties</code> set as above, the only file it writes there, the generated <code>fmr.properties</code>, lands in <code>tools/fmr/runtime/home/</code>, and no <code>SDMX_IO</code> folder appears in the user profile. FMR’s own logs go to <code>tools/fmr/runtime/tomcat/logs/</code>.</li>
<li>The setup page’s calls need a session cookie from <code>install.html</code>; without it they return HTTP 401.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/wbEAWPV\.github\.io\/AFW360_Glance\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 World Bank Group</p>
</div>   
    <div class="nav-footer-center">
<p>AFW360 - Platform Concept · draft v0.6</p>
</div>
    <div class="nav-footer-right">
<p><a href="https://github.com/wbEAWPV/AFW360_Glance">Source</a></p>
</div>
  </div>
</footer>




</body></html>