<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-21">

<title>Appendix B.1. AFW 360 transition plan – AFW 360 data standard</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-172ba59bd5e0b52282274ba0c0cc16fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../styles.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">AFW 360 data standard</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Standard</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../input-tables-findings.html"> 
<span class="menu-text">Appendix A · Input tables</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-appendix-b-·-transition" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Appendix B · Transition</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-appendix-b-·-transition">    
        <li>
    <a class="dropdown-item" href="../transition/plan.html">
 <span class="dropdown-text">B.1 · Plan</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../transition/contract.html">
 <span class="dropdown-text">B.2 · Contract</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../transition/decisions.html">
 <span class="dropdown-text">B.3 · Decisions</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/wbEAWPV/AFW360_Glance"> <i class="bi bi-github" role="img" aria-label="Source repository on GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#sec-docset" id="toc-sec-docset" class="nav-link active" data-scroll-target="#sec-docset"><span class="header-section-number">1</span> The document set</a></li>
  <li><a href="#sec-start" id="toc-sec-start" class="nav-link" data-scroll-target="#sec-start"><span class="header-section-number">2</span> Starting point</a>
  <ul class="collapse">
  <li><a href="#sec-inventory" id="toc-sec-inventory" class="nav-link" data-scroll-target="#sec-inventory"><span class="header-section-number">2.1</span> Inventory</a></li>
  <li><a href="#sec-tables-brief" id="toc-sec-tables-brief" class="nav-link" data-scroll-target="#sec-tables-brief"><span class="header-section-number">2.2</span> What shapes the transition</a></li>
  </ul></li>
  <li><a href="#sec-end" id="toc-sec-end" class="nav-link" data-scroll-target="#sec-end"><span class="header-section-number">3</span> End point</a></li>
  <li><a href="#sec-decisions" id="toc-sec-decisions" class="nav-link" data-scroll-target="#sec-decisions"><span class="header-section-number">4</span> Decisions this plan rests on</a></li>
  <li><a href="#sec-run" id="toc-sec-run" class="nav-link" data-scroll-target="#sec-run"><span class="header-section-number">5</span> How the transition runs</a>
  <ul class="collapse">
  <li><a href="#sec-principles" id="toc-sec-principles" class="nav-link" data-scroll-target="#sec-principles"><span class="header-section-number">5.1</span> Principles</a></li>
  <li><a href="#sec-roles" id="toc-sec-roles" class="nav-link" data-scroll-target="#sec-roles"><span class="header-section-number">5.2</span> Roles</a></li>
  <li><a href="#sec-packages" id="toc-sec-packages" class="nav-link" data-scroll-target="#sec-packages"><span class="header-section-number">5.3</span> Packages</a></li>
  <li><a href="#sec-waves" id="toc-sec-waves" class="nav-link" data-scroll-target="#sec-waves"><span class="header-section-number">5.4</span> Waves and gates</a></li>
  <li><a href="#sec-lifecycle" id="toc-sec-lifecycle" class="nav-link" data-scroll-target="#sec-lifecycle"><span class="header-section-number">5.5</span> Package life cycle</a></li>
  <li><a href="#sec-branches" id="toc-sec-branches" class="nav-link" data-scroll-target="#sec-branches"><span class="header-section-number">5.6</span> Branches</a></li>
  </ul></li>
  <li><a href="#sec-targets" id="toc-sec-targets" class="nav-link" data-scroll-target="#sec-targets"><span class="header-section-number">6</span> Verification</a></li>
  <li><a href="#sec-risks" id="toc-sec-risks" class="nav-link" data-scroll-target="#sec-risks"><span class="header-section-number">7</span> Risks and pitfalls</a></li>
  <li><a href="#sec-after" id="toc-sec-after" class="nav-link" data-scroll-target="#sec-after"><span class="header-section-number">8</span> After the transition</a></li>
  <li><a href="#sec-revision" id="toc-sec-revision" class="nav-link" data-scroll-target="#sec-revision"><span class="header-section-number">9</span> What changed in revision 2</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Appendix B.1. AFW 360 transition plan</h1>
<p class="subtitle lead">From the legacy Excel, shapefile and text inputs to the AFW360 data standard · revision 2</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This plan converts the dashboard’s current inputs (two Excel workbooks, 22 shapefile layers, a handful of text files and one image) into the files defined by the <a href="../index.html">data standard</a>:</p>
<ul>
<li>codelists and plans under <code>metadata/</code>;</li>
<li>one long CSV per country and year under <code>data/</code>;</li>
<li>boundaries under <code>geo/</code>;</li>
<li>prose and images under <code>content/</code> and <code>assets/</code>.</li>
</ul>
<p>Every file is produced by R code under <code>pipeline/</code>, so the conversion can be read, rerun and checked. The dashboard keeps working throughout, and it switches to the new files only after this plan is complete.</p>
<p>The plan is carried out by agents working in parallel. An <strong>orchestrator</strong> running on Opus launches them and takes decisions to the user, and it never edits or runs anything itself. <strong>Implementers, verifiers, patch agents and integrators</strong> running on Sonnet do all the work. Each package is checked by a verifier that did not build it. The user decides at three gates, and nothing becomes <code>ACTIVE</code> without the user.</p>
<p>Revision 2 follows a review of the first plan; <a href="#sec-revision" class="quarto-xref">Section&nbsp;9</a> lists what changed and why.</p>
<section id="sec-docset" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> The document set</h1>
<div id="tbl-docset" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-docset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The transition documents
</figcaption>
<div aria-describedby="tbl-docset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>File</th>
<th>What it is</th>
<th>Who reads it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>plan.qmd</code> (this file)</td>
<td>Starting point, end point, packages, waves, gates and risks</td>
<td>The orchestrator and the user</td>
</tr>
<tr class="even">
<td><code>packages/COMMON.md</code></td>
<td>The rules every agent follows, including the context budget</td>
<td>Every agent</td>
</tr>
<tr class="odd">
<td><code>packages/WPNN.md</code></td>
<td>One self-contained card per package, holding everything that package’s agents need</td>
<td>That package’s implementer, verifier and patch agents</td>
</tr>
<tr class="even">
<td><a href="../transition/contract.html"><code>contract.qmd</code></a></td>
<td>The reference for shared interfaces, formats, grammar and tolerances</td>
<td>The user; agents only where a card says so</td>
</tr>
<tr class="odd">
<td><code>contract/*.csv</code> and <code>contract/check_contract.R</code></td>
<td>The machine-readable contract: codes, label triage, plan, column maps, overrides, headers, ownership and expected counts, plus a script that checks them against each other and against the workbooks</td>
<td>Agents, through filtered look-ups; the integrator</td>
</tr>
<tr class="even">
<td><a href="../transition/decisions.html"><code>decisions.qmd</code></a></td>
<td>Decisions taken, hard cases for gate G0, and gaps in the standard</td>
<td>The user; WP02 and WP99, by section</td>
</tr>
<tr class="odd">
<td><code>templates/</code></td>
<td>The four role prompts, the scout prompt, the gate questions and the acceptance-script skeleton</td>
<td>The orchestrator</td>
</tr>
<tr class="even">
<td><code>orchestrator-prompt.md</code></td>
<td>The prompt that starts, or resumes, the orchestrator</td>
<td>The user</td>
</tr>
<tr class="odd">
<td><code>STATUS.md</code> and <code>reports/</code></td>
<td>The board kept by the integrators on <code>transition/main</code>, and every agent’s report</td>
<td>The user; scouts</td>
</tr>
<tr class="even">
<td><a href="../index.html"><code>../data-standard.qmd</code></a></td>
<td>The target format (v0.3; WP02 turns it into v0.4)</td>
<td>WP02 whole; the others not at all</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Cards are self-contained.</strong> A card carries the rules its package needs, taken from the standard, the contract and the decisions. An agent therefore reads two short files and a few filtered rows, not the whole document set. <strong>Machine-readable files win.</strong> Where prose and a <code>contract/*.csv</code> file disagree, the CSV is right, and the disagreement is reported.</p>
</section>
<section id="sec-start" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Starting point</h1>
<p>This is what the repository holds on 2026-09-21, on branch <code>dev/eb</code>. WP00 tags the starting commit as <code>transition-base</code>.</p>
<section id="sec-inventory" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="sec-inventory"><span class="header-section-number">2.1</span> Inventory</h2>
<p>There are 122 tracked legacy files. WP01 moves every one of them to <code>data_raw/</code>.</p>
<div id="tbl-inventory" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-inventory-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Legacy files on 2026-09-21
</figcaption>
<div aria-describedby="tbl-inventory-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Current location</th>
<th>Files</th>
<th>Content</th>
<th>Read by the dashboard</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>INPUT Tables/Tables_SEN.xlsx</code></td>
<td>1</td>
<td>Four sheets: <code>National</code> 97 × 13, <code>ADM 1</code> 97 × 14, <code>ZAE</code> 97 × 6, <code>Departement</code> 82 × 14</td>
<td>Yes (<code>National</code>, <code>ADM 1</code>, <code>ZAE</code>)</td>
</tr>
<tr class="even">
<td><code>INPUT Tables/Tables_GNB.xlsx</code></td>
<td>1</td>
<td>Three sheets: <code>National</code> 97 × 13, <code>ADM 1</code> 97 × 9, <code>ZAE</code> 97 × 4</td>
<td>Only for the About-page download; the GNB section reads the SEN file (known bug)</td>
</tr>
<tr class="odd">
<td><code>INPUT Tables/Tables_SEN_TEST.xlsx</code></td>
<td>1</td>
<td>Scratch</td>
<td>No</td>
</tr>
<tr class="even">
<td><code>INPUT shp/</code></td>
<td>110</td>
<td>22 layers × 5 side-car files</td>
<td><code>sen_admin1.shp</code> only</td>
</tr>
<tr class="odd">
<td><code>INPUT Text/</code></td>
<td>6</td>
<td>The About texts (<code>About.txt</code> and <code>About_SEN.txt</code> are byte-identical; <code>About_GNB.txt</code> is the placeholder <code>TEXT</code>), the key messages, and one scratch file</td>
<td>The About texts only; the key messages are hard-coded in <code>index.qmd</code> in a different version</td>
</tr>
<tr class="even">
<td><code>INPUT Figures/Fiscal Equity SEN.png</code></td>
<td>1</td>
<td>Fiscal-equity chart</td>
<td>Yes, in the SEN <strong>and</strong> GNB sections (known bug)</td>
</tr>
<tr class="odd">
<td><code>dsf.qqqww</code>, <code>map_test.png</code></td>
<td>2</td>
<td>Scratch</td>
<td>No</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>index.qmd</code> refers to these inputs by path in 12 places: lines 188, 370, 371, 658, 665, 675, 694, 1115, 1122, 1132, 1151 and 1182. WP01 changes only those strings.</p>
</section>
<section id="sec-tables-brief" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-tables-brief"><span class="header-section-number">2.2</span> What shapes the transition</h2>
<p>The full findings are in <a href="../input-tables-findings.html">input-tables-findings.qmd</a>.</p>
<ul>
<li>Each sheet is a set of one-way breakdowns of the national population. Breakdowns are never crossed.</li>
<li>Rows are identified only by 97 free-text labels, which are byte-identical across sheets and countries. The poverty line, PPP round, unit and classification are all written inside the label.</li>
<li>Values are rounded to 2 decimals and stored as shares (0–1) or levels, with no unit field. An empty cell is ambiguous.</li>
<li>Regions and zones are identified by spelled names. Some names are cut at 32 characters, and GNB’s names carry accents. The COD-AB P-codes are already in the shapefiles (<code>SN01</code>–<code>SN14</code>, <code>GW01</code>–<code>GW09</code>); Bissau is <code>GW08</code>, which the tables call <code>SAB</code>.</li>
<li>Two SEN polygons, SN01 and SN13, are invalid as delivered.</li>
</ul>
<div id="tbl-defects" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-defects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Defects in the inputs and where the plan handles them
</figcaption>
<div aria-describedby="tbl-defects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Defect</th>
<th>Handled by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GNB <code>Capital</code> column is a copy of a zone; 7 other GNB cultivated-area cells run into the millions of hectares</td>
<td>Withheld: their rows are absent, and each is registered (D5; <code>contract/legacy_overrides.csv</code>)</td>
</tr>
<tr class="even">
<td>SEN <code>Departement</code> sheet is an older version with mislabelled PPP</td>
<td>Skipped (D3)</td>
</tr>
<tr class="odd">
<td>Duplicate series (Food share = COICOP 1; Housing burden = COICOP 4) and derivable series</td>
<td><code>DUPLICATE_OF</code> and <code>DERIVED</code> labels, with the relation asserted by the converter</td>
</tr>
<tr class="even">
<td>Empty or implausible series</td>
<td><code>SKIP</code>, or a <code>COMMENT</code> override; the user confirms at gate G0 (H7, H9, H12, H14)</td>
</tr>
<tr class="odd">
<td>Undocumented cut-off for household-head age</td>
<td>DRAFT codes (H17)</td>
</tr>
<tr class="even">
<td>No geographic codes; names truncated at 32 characters</td>
<td><code>contract/geo_codes.csv</code></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-end" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> End point</h1>
<p>When the plan is complete, the repository holds the layout below. Everything in it is <code>DRAFT</code> until the user promotes it.</p>
<pre><code>data_raw/                  the 122 legacy files, byte-frozen, with checksums
metadata/                  VERSION 0.1.0, CHANGELOG, structure/ (DSD, COLUMNS), codelists/, surveys/, plans/, registries/
data/                      AFW360_HH_SEN_2021.csv, AFW360_HH_GNB_2021.csv, and a manifest for each
geo/boundaries/            SEN_CODAB_v02.gpkg, GNB_CODAB_V01.gpkg (layers adm0, adm1)
content/                   TEXT.csv, text/SEN/about.md
assets/figures/SEN/        the fiscal-equity figure
pipeline/
  R/                       io, constants, codes, ctx, plan, geo, content, convert_tables, manifest, reconcile, validate_*
  bootstrap/               one-time generators of the metadata files, and their text seeds
  build_geo.R  build_content.R  convert_legacy.R  validate.R  reconcile.R
  tests/testthat/          unit tests
  acceptance/              one independent acceptance script per package, plus run_all.R</code></pre>
<div id="tbl-outcomes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-outcomes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Expected outcomes
</figcaption>
<div aria-describedby="tbl-outcomes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Outcome</th>
<th>Expected (<code>contract/expected_counts.csv</code> is authoritative)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SEN data file</td>
<td>3,003 observations: 91 series × 33 groups, all <code>OBS_STATUS=A</code></td>
</tr>
<tr class="even">
<td>GNB data file</td>
<td>2,366 mapped cells less 98 withheld: 2,268 observations, of which 2,229 are <code>A</code> and 39 are <code>O</code></td>
</tr>
<tr class="odd">
<td>Source accounting</td>
<td>SEN 3,201 cells and GNB 2,522 cells, each traced exactly once; all 1,148 <code>Departement</code> cells skipped</td>
</tr>
<tr class="even">
<td>Poverty counts (persons)</td>
<td>SEN 3.13M / 6.52M and GNB 0.70M / 1.09M at $3.00 / $4.20 (2021 PPP)</td>
</tr>
<tr class="odd">
<td>Dictionary</td>
<td>62 indicator codes, 91 series, 8 cuts, 13 breakdown variables with 60 categories, 6 qualifier variables with 42 categories</td>
</tr>
<tr class="even">
<td>Geography</td>
<td>35 spatial units in 6 schemes; 2 GeoPackages</td>
</tr>
<tr class="odd">
<td>Legacy maps</td>
<td>179 labels, 73 columns, 12 overrides</td>
</tr>
<tr class="even">
<td>Text and assets</td>
<td>8 text entries, 1 figure, 2 surveys</td>
</tr>
<tr class="odd">
<td>Checks</td>
<td>0 validator errors; byte-identical re-runs; every source cell reconciled</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A hard-case flip at gate G0 changes some of these numbers. WP99 then updates <code>expected_counts.csv</code>, and every check reads its targets from that file.</p>
<p><strong>What does not change.</strong> The dashboard still reads the legacy files, from <code>data_raw/</code> after WP01. No value is recomputed from microdata: the transition restructures and documents what the workbooks contain, and withholds what is known to be wrong.</p>
</section>
<section id="sec-decisions" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Decisions this plan rests on</h1>
<p>The full record is in <a href="../transition/decisions.html">decisions.qmd</a>.</p>
<ul>
<li><strong>D1 Tooling.</strong> The metadata bootstrap, converter and validator are written in R. The dashboard stays Python.</li>
<li><strong>D2 Raw inputs.</strong> All legacy files move to <code>data_raw/</code>, byte-identical.</li>
<li><strong>D3 <code>Departement</code>.</strong> The sheet is skipped entirely.</li>
<li><strong>D4 Shares.</strong> Three codes: <code>POP_SH</code>, <code>POP_HH_SH</code> and <code>POP_HE_SH</code>.</li>
<li><strong>D5 Defective cells.</strong> Their rows are absent, and each is registered.</li>
<li><strong>D6 GNB survey.</strong> EHCVM 2021/22, <code>TIME_PERIOD=2021</code>.</li>
<li><strong>D7 and D10 Hard cases.</strong> They are built with the recommended coding as DRAFT, and the user confirms or flips each <strong>at gate G0, before anything is built</strong>.</li>
<li><strong>D8 Execution.</strong> Parallel agents only. The Opus orchestrator never executes; Sonnet agents do the work.</li>
<li><strong>D9 Empty legacy cells.</strong> <code>OBS_STATUS=O</code>, with a <code>LEGACY_EMPTY:</code> comment.</li>
<li><strong>D11 Metadata by code.</strong> Every metadata file is generated by a script under <code>pipeline/bootstrap/</code> from the contract seeds and an authored text file. From version 0.1.0 onward the CSV files are the source of truth.</li>
<li><strong>D12 Line endings.</strong> <code>.gitattributes</code> pins generated text to LF and marks <code>data_raw/</code> as binary.</li>
</ul>
</section>
<section id="sec-run" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> How the transition runs</h1>
<section id="sec-principles" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-principles"><span class="header-section-number">5.1</span> Principles</h2>
<ol type="1">
<li><strong>Small context.</strong>
<ul>
<li>An agent reads <code>COMMON.md</code>, its card, and a few filtered rows: about 10,000 to 25,000 tokens.</li>
<li>Its whole session stays under 100,000 tokens, and 150,000 is the hard limit.</li>
<li>An agent that runs long stops, and reports <code>PARTIAL</code>. A fresh agent then continues.</li>
</ul></li>
<li><strong>Contract first.</strong> The packages of a wave build against the contract seeds, not against each other’s output. <code>contract/check_contract.R</code> proves that the seeds agree with each other and with the workbooks.</li>
<li><strong>Code, not typing.</strong>
<ul>
<li>Metadata files are generated by scripts from the seeds.</li>
<li>Agents write text (names, definitions) only where there is no source for it.</li>
<li>Every generator can rebuild into a temporary directory, so any file can be checked by regenerating it.</li>
</ul></li>
<li><strong>Real inputs for the validator.</strong> The validator is written in wave 3 against the real, merged metadata, never against invented fixtures.</li>
<li><strong>Ownership.</strong> Every output path has exactly one owner in <code>contract/output_ownership.csv</code>. An agent that needs another path stops and reports.</li>
<li><strong>Independent verification.</strong> The verifier writes its own acceptance script from the card. The scripts are kept, and they are rerun after every merge.</li>
<li><strong>State in git.</strong> Branch names and commit subjects (<code>WP05: verify v1 - VERDICT: PASS</code>) record the state of the run. A new orchestrator session resumes from them.</li>
<li><strong>Nothing is pushed,</strong> and nothing reaches <code>dev/eb</code> before the user says so at G2.</li>
</ol>
</section>
<section id="sec-roles" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-roles"><span class="header-section-number">5.2</span> Roles</h2>
<div id="tbl-roles" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-roles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Roles; the prompts are in <code>templates/</code>
</figcaption>
<div aria-describedby="tbl-roles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Model</th>
<th>Runs as</th>
<th>Writes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Orchestrator</td>
<td>Opus</td>
<td>The main session</td>
<td>Nothing</td>
</tr>
<tr class="even">
<td>Implementer</td>
<td>Sonnet</td>
<td><code>Agent</code>, worktree</td>
<td>The package’s owned outputs and its report</td>
</tr>
<tr class="odd">
<td>Verifier</td>
<td>Sonnet</td>
<td><code>Agent</code>, worktree; fresh for each attempt</td>
<td><code>pipeline/acceptance/wpNN_&lt;slug&gt;.R</code> and its report</td>
</tr>
<tr class="even">
<td>Patch agent</td>
<td>Sonnet</td>
<td><code>Agent</code>, worktree</td>
<td>The package’s owned outputs and its report</td>
</tr>
<tr class="odd">
<td>Integrator</td>
<td>Sonnet</td>
<td><code>Agent</code>, worktree; one per wave</td>
<td>Merges on <code>transition/main</code>; <code>CHANGELOG.md</code>, <code>STATUS.md</code>, gate records, wave and final reports</td>
</tr>
<tr class="even">
<td>Scout</td>
<td>Sonnet</td>
<td><code>Agent</code>, <code>Explore</code>, read-only</td>
<td>Nothing</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-packages" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-packages"><span class="header-section-number">5.3</span> Packages</h2>
<div id="tbl-packages" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-packages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Packages. The card is <code>packages/WPNN.md</code>
</figcaption>
<div aria-describedby="tbl-packages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>WP</th>
<th>Title</th>
<th>Wave</th>
<th>Slug</th>
<th>Depends on</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>WP00</td>
<td>Setup and environment check (no verifier)</td>
<td>0</td>
<td><code>setup</code></td>
<td>—</td>
</tr>
<tr class="even">
<td>WP01</td>
<td>Move legacy inputs to <code>data_raw/</code></td>
<td>1</td>
<td><code>data-raw</code></td>
<td>WP00</td>
</tr>
<tr class="odd">
<td>WP02</td>
<td>Data standard v0.4 (stage A, then stage B)</td>
<td>1</td>
<td><code>standard-v04</code></td>
<td>WP00</td>
</tr>
<tr class="even">
<td>WP03</td>
<td>Pipeline scaffold</td>
<td>1</td>
<td><code>scaffold</code></td>
<td>WP00</td>
</tr>
<tr class="odd">
<td>WP99</td>
<td>Apply G0 answers to the contract (only if a case is flipped)</td>
<td>1</td>
<td><code>contract-flips</code></td>
<td>G0</td>
</tr>
<tr class="even">
<td>WP04</td>
<td>Small codelists and <code>CL_AREA</code></td>
<td>2</td>
<td><code>small-codelists</code></td>
<td>W1, G1</td>
</tr>
<tr class="odd">
<td>WP05</td>
<td>Geography</td>
<td>2</td>
<td><code>geography</code></td>
<td>W1, G1</td>
</tr>
<tr class="even">
<td>WP06</td>
<td>Breakdowns and qualifiers</td>
<td>2</td>
<td><code>breakdowns-qualifiers</code></td>
<td>W1, G1</td>
</tr>
<tr class="odd">
<td>WP07</td>
<td>Indicator dictionary</td>
<td>2</td>
<td><code>dictionary</code></td>
<td>W1, G1</td>
</tr>
<tr class="even">
<td>WP08</td>
<td>Plans and the required-row generator</td>
<td>2</td>
<td><code>plans</code></td>
<td>W1, G1</td>
</tr>
<tr class="odd">
<td>WP09</td>
<td>Legacy maps</td>
<td>2</td>
<td><code>legacy-maps</code></td>
<td>W1, G1</td>
</tr>
<tr class="even">
<td>WP10</td>
<td>Text, figures and surveys</td>
<td>2</td>
<td><code>content</code></td>
<td>W1, G1</td>
</tr>
<tr class="odd">
<td>WP11</td>
<td>Validator core: structure, codes, metadata</td>
<td>3</td>
<td><code>validator-core</code></td>
<td>W2</td>
</tr>
<tr class="even">
<td>WP12</td>
<td>Validator: coverage and values</td>
<td>3</td>
<td><code>validator-coverage</code></td>
<td>W2</td>
</tr>
<tr class="odd">
<td>WP13</td>
<td>Validator: verification rules</td>
<td>3</td>
<td><code>validator-rules</code></td>
<td>W2</td>
</tr>
<tr class="even">
<td>WP14</td>
<td>Validator: assets and text</td>
<td>3</td>
<td><code>validator-assets-text</code></td>
<td>W2</td>
</tr>
<tr class="odd">
<td>WP15</td>
<td>Legacy converter</td>
<td>3</td>
<td><code>converter</code></td>
<td>W2</td>
</tr>
<tr class="even">
<td>WP16</td>
<td>Independent reconciliation tool</td>
<td>3</td>
<td><code>reconcile</code></td>
<td>W2</td>
</tr>
<tr class="odd">
<td>WP17</td>
<td>Final audit (verifier only)</td>
<td>after W3</td>
<td><code>final-audit</code></td>
<td>W3</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Names derive from the table. The implementer branch is <code>transition/wpNN-&lt;slug&gt;</code>, verifier branches add <code>-v&lt;K&gt;</code>, and patch branches add <code>-p&lt;K&gt;</code>. The acceptance script is <code>pipeline/acceptance/wpNN_&lt;slug&gt;.R</code>. Reports are <code>reports/WPNN-implementer.md</code>, <code>WPNN-implementer-p&lt;K&gt;.md</code> and <code>WPNN-verifier-v&lt;K&gt;.md</code>.</p>
</section>
<section id="sec-waves" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-waves"><span class="header-section-number">5.4</span> Waves and gates</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TB
  W0[W0: WP00 setup and environment check] --&gt; W1
  subgraph W1[Wave 1]
    WP01 &amp; WP02A[WP02 stage A] &amp; WP03 &amp; WP99[WP99 if flips]
    WP02A --&gt; WP02B[WP02 stage B]
  end
  G0{{G0: hard cases, asked while wave 1 runs}} -.-&gt; WP99
  W1 --&gt; G1{{G1: standard v0.4 and contract}}
  G1 --&gt; W2
  subgraph W2[Wave 2: metadata and assets]
    WP04 &amp; WP05 &amp; WP06 &amp; WP07 &amp; WP08 &amp; WP09 &amp; WP10
  end
  W2 --&gt; W3
  subgraph W3[Wave 3: validator, converter, reconciliation]
    WP11 &amp; WP12 &amp; WP13 &amp; WP14 &amp; WP15 &amp; WP16
  end
  W3 --&gt; A[WP17 final audit] --&gt; G2{{G2: accept, merge to dev/eb}}
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div id="tbl-waves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-waves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Waves
</figcaption>
<div aria-describedby="tbl-waves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Wave</th>
<th>Packages (in parallel)</th>
<th>Then</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>W0</td>
<td>WP00 creates <code>transition/main</code> and the tag <code>transition-base</code>, and proves that R, the packages, the contract check and the dashboard render all work</td>
<td>Stops the run if the environment is broken</td>
</tr>
<tr class="even">
<td>W1</td>
<td>WP01 ∥ WP02 (A then B) ∥ WP03, and WP99 if a case is flipped. <strong>G0</strong> is asked while they run.</td>
<td>Integrator: contract check, checksums, dashboard render, G0 record. Then <strong>G1</strong>.</td>
</tr>
<tr class="odd">
<td>W2</td>
<td>WP04 ∥ WP05 ∥ WP06 ∥ WP07 ∥ WP08 ∥ WP09 ∥ WP10</td>
<td>Integrator: every file present with its header; the required rows from the real metadata equal the expected counts; G1 record</td>
</tr>
<tr class="even">
<td>W3</td>
<td>WP11 ∥ WP12 ∥ WP13 ∥ WP14 ∥ WP15 ∥ WP16</td>
<td>Integrator: the converter reproduces <code>data/</code>; full validation; reconciliation. Findings go to the owning package as patches, until the run is clean.</td>
</tr>
<tr class="odd">
<td>After W3</td>
<td>WP17 final audit</td>
<td><strong>G2</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Why the waves fall where they do.</strong></p>
<ul>
<li>Wave 2 needs the scaffold’s writer functions (WP03), the inputs in <code>data_raw/</code> (WP01) and a frozen contract (G1).</li>
<li>Wave 3 needs the real metadata. The validator is tested on it; the converter reads it; and the reconciliation tool is written at the same time as the converter, without seeing its code, so that it checks the converter independently.</li>
<li>The hard cases are asked first because every answer can be given from the evidence already in <code>decisions.qmd</code>. Asked first, a flip costs one edit of the seeds. Asked after the build, it would cost patches in up to three packages, and it would change counts that the acceptance scripts had already fixed.</li>
</ul>
<div id="tbl-gates" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Gates; the questions are in <code>templates/gate-review.md</code>
</figcaption>
<div aria-describedby="tbl-gates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Gate</th>
<th>When</th>
<th>The user decides</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>G0</td>
<td>At the start, while wave 1 runs</td>
<td>For each open hard case (H1–H14, H17): recommended, alternative, or another answer. Also which version of the key messages is authoritative (T1).</td>
</tr>
<tr class="even">
<td>G1</td>
<td>After the wave-1 integration</td>
<td>Approve standard v0.4 and the contract, approve with notes, or hold. On approval the contract is frozen.</td>
</tr>
<tr class="odd">
<td>G2</td>
<td>After WP17 passes</td>
<td>Accept the results; merge <code>transition/main</code> into <code>dev/eb</code> now or later</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-lifecycle" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-lifecycle"><span class="header-section-number">5.5</span> Package life cycle</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  I[Implementer] --&gt;|DONE| V[Fresh verifier]
  I --&gt;|PARTIAL| C[Patch agent: CONTINUE] --&gt; V
  V --&gt;|PASS| R[Ready for the integrator]
  V --&gt;|FAIL| P[Patch agent: FAILURES] --&gt; V2[Fresh verifier]
  V2 --&gt;|PASS| R
  V2 --&gt;|FAIL, 2 patches used| U[Ask the user]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>After every merge, the integrator reruns every acceptance script written so far, plus the unit tests. A failure is reported against the package that owns the broken file, and that package gets a patch agent. The integrator never fixes anything. It ends with one of three statuses: <code>INTEGRATED</code>; <code>FINDINGS</code>, when every failure has an owning package, so patch agents are sent without asking the user; or <code>BLOCKED</code>, when a branch cannot be merged or a failure has no owner, which goes to the user. A failed WP17 audit is handled like integrator findings: patches, a follow-up wave-3 integration, then the audit again as <code>v2</code>. Validator findings on the real data at wave 3 go first to the package that owns the check (<code>FINDINGS</code> mode): that agent decides, from its card’s rules, whether the check or the data is wrong.</p>
</section>
<section id="sec-branches" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-branches"><span class="header-section-number">5.6</span> Branches</h2>
<pre><code>dev/eb ──(WP00)──► transition/main ◄── integrator merges PASS branches, wave by wave
   │ tag: transition-base  │
                           ├── transition/wp05-geography          implementer
                           │     └── …-v1                           verifier: acceptance script and report
                           │           └── …-p1 ── …-v2             patch after a FAIL, then a fresh verifier
                           └── …</code></pre>
<p>Every agent ends with <code>git switch --detach</code>, so that no worktree keeps a branch locked. If an agent dies before that step, a scout finds the stale worktree, and the rerun frees the branch with <code>git -C &lt;stale worktree&gt; switch --detach</code>, which deletes nothing. WP00 can be run again after a failed environment check: its card treats the second run as a retry. The final merge into <code>dev/eb</code> takes WP17’s PASS branch, which is <code>transition/main</code> plus the audit.</p>
</section>
</section>
<section id="sec-targets" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Verification</h1>
<p>Verification happens at four levels.</p>
<ol type="1">
<li><strong>The contract is checked before it is used.</strong> <code>check_contract.R</code> runs in WP00, in the wave-1 integration, and after any flip. It checks:
<ul>
<li>code syntax and references;</li>
<li>the series-ID rule;</li>
<li>labels and columns, byte for byte against the workbooks;</li>
<li>that the plan’s row count equals the count of mapped workbook cells (3,003 and 2,366);</li>
<li>every <code>EQUALS</code> and <code>ONE_MINUS</code> assertion on the raw cells;</li>
<li>every recomputable number in <code>expected_counts.csv</code>.</li>
</ul></li>
<li><strong>Every package is checked by an independent script</strong> from its card. The scripts are committed, and they rerun after each merge (<code>pipeline/acceptance/run_all.R</code>). They compare against the tag <code>transition-base</code> and against files, so they keep passing after the merge.</li>
<li><strong>The wave-3 integration</strong> runs the converter, the validator and the reconciliation on everything together.</li>
<li><strong>The final audit (WP17)</strong> checks every row of <code>expected_counts.csv</code> against the finished repository, and produces the tables shown at G2.</li>
</ol>
<p>The validator’s aggregation, closure, monotonicity and range rules were tested against the raw workbooks when this plan was written. With the contract’s tolerances, the legacy data break none of them: 980 aggregation checks ran, and 112 were skipped for withheld or empty cells.</p>
</section>
<section id="sec-risks" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Risks and pitfalls</h1>
<ul>
<li><strong>Context overrun.</strong> The first plan made every agent read about 110,000 tokens before starting. Cards are now self-contained; <code>COMMON.md</code> section 1 sets the reading and output rules; and a long session ends as <code>PARTIAL</code> instead of degrading.</li>
<li><strong>Line endings.</strong> <code>core.autocrlf=true</code> would check generated CSVs out with CRLF in every new worktree. <code>.gitattributes</code> pins them to LF and marks <code>data_raw/**</code> as binary. WP01 restores the exact bytes after the move, and checks that look at bytes use git blobs.</li>
<li><strong>Environment.</strong> Quarto needs <code>QUARTO_R</code> unset and <code>QUARTO_PYTHON="C:/WBG/Python313/python.exe"</code>. WP00 proves the render before anything else runs.</li>
<li><strong>Silent type changes.</strong> Read every CSV with all columns as character, write NA as an empty string, and never let a number print in scientific notation.</li>
<li><strong>Encoding.</strong> Workbook headers carry accents, labels carry <code>–</code> and <code>≥</code>, and one sheet is named <code>ADM 1</code>. Match them byte for byte; never retype them.</li>
<li><strong>Geometry.</strong> Build with GEOS (<code>sf_use_s2(FALSE)</code>) and <code>st_make_valid</code>. A GeoPackage’s bytes change on every build, so it is compared by content.</li>
<li><strong>Validator against real data.</strong> The first full validation can show errors that are the validator’s own. The wave-3 loop sends each finding to the check’s owner first, which decides where the fault lies.</li>
<li><strong>Parallel collisions.</strong> A path owned twice, or a merge conflict outside the integrator’s own files, is a defect in the contract. The integrator aborts that merge and reports it.</li>
<li><strong>Scope creep.</strong> Agents do not fix defects in the inputs. They register them.</li>
<li><strong>Worktrees pile up.</strong> Each agent leaves a worktree behind. After G2, the user can remove them with <code>git worktree list</code> and <code>git worktree remove &lt;path&gt;</code>; every branch stays in the repository.</li>
</ul>
</section>
<section id="sec-after" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> After the transition</h1>
<p>These steps are out of scope for this plan:</p>
<ul>
<li>Point the dashboard at <code>data/</code>, <code>metadata/</code>, <code>geo/</code> and <code>content/</code> through one loader per country (objective 3 in CLAUDE.md), and fix the display bugs listed there.</li>
<li>Promote confirmed codes from <code>DRAFT</code> to <code>ACTIVE</code>, and replace the legacy files with producer files that carry <code>N_OBS</code>, <code>N_POP</code> and standard errors.</li>
<li>Freeze <code>pipeline/bootstrap/</code>: from metadata 0.1.0 onward the CSV files are edited by hand through pull requests (D11).</li>
<li>Resolve the decisions that the standard leaves open (see <a href="../transition/decisions.html">decisions.qmd</a>), including <code>content/SLOTS.csv</code> (gap p).</li>
</ul>
</section>
<section id="sec-revision" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> What changed in revision 2</h1>
<div id="tbl-revision" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-revision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Review findings and the changes made
</figcaption>
<div aria-describedby="tbl-revision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Problem found in the review</th>
<th>Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The role prompts made every agent read the whole standard, the decisions and every contract CSV: about 113,000 tokens before any work</td>
<td>One self-contained card per package (<code>packages/</code>), a common rule sheet with a context budget, and filtered look-ups into the CSVs</td>
</tr>
<tr class="even">
<td>The dashboard did not render from an agent’s shell (wrong Python, broken <code>QUARTO_R</code>)</td>
<td>Both are fixed in <code>COMMON.md</code>, and WP00 proves the environment first</td>
</tr>
<tr class="odd">
<td>Acceptance scripts compared against the moving <code>transition/main</code>, so they would fail once merged</td>
<td>The tag <code>transition-base</code>; scripts compare against the tag and against files</td>
</tr>
<tr class="even">
<td>Reports were written after the commit, and so were never committed</td>
<td>Report first, then one commit; the verdict goes in the commit subject</td>
</tr>
<tr class="odd">
<td>A hard-case flip at G1 changed counts that nobody was allowed to update</td>
<td>The hard cases are asked at G0, before the build, and WP99 applies flips to the seeds and recomputes the counts</td>
</tr>
<tr class="even">
<td>The validator was built against invented fixtures, in parallel with the metadata</td>
<td>The validator packages moved to wave 3, and they test on the real metadata through shared fixture helpers</td>
</tr>
<tr class="odd">
<td>The metadata was hand-typed, with no code behind it</td>
<td>Each metadata package writes a generator under <code>pipeline/bootstrap/</code> (D11)</td>
</tr>
<tr class="even">
<td>Code lists existed only as prose with ellipses, and several tables contradicted each other</td>
<td><code>contract/codes.csv</code>, <code>tab_plan.csv</code>, <code>legacy_national_columns.csv</code> and <code>legacy_overrides.csv</code>, checked by <code>check_contract.R</code>; the duplicate tables are gone</td>
</tr>
<tr class="odd">
<td><code>POP_SH</code> carried two reference periods, which the contract check found</td>
<td>Gap (z): the recall period belongs to the breakdown’s universe</td>
</tr>
<tr class="even">
<td>CRLF on checkout would break the LF and byte-identity checks</td>
<td><code>.gitattributes</code> (D12)</td>
</tr>
<tr class="odd">
<td>WP00 and WP15 spent five agent runs on a branch and a report; the scribe spent three on copying answers</td>
<td>WP00 has no verifier; the wave-3 integrator and the WP17 audit replace the old WP15; the integrators record the gates</td>
</tr>
<tr class="even">
<td>WP02 and the old WP11 were too large for one session</td>
<td>WP02 runs in two stages; the validator is four packages; the required-row generator has its own package (WP08)</td>
</tr>
<tr class="odd">
<td>A read-only dry run by seven Sonnet readers (2026-09-21) found read lists that missed needed files (WP08, WP11, WP15, WP16, WP17), a findings <code>row_key</code> defined on one card only, an integrator <code>BLOCKED</code> that meant two things, no way to rerun WP00 or to recover a dead agent, and no loop after a failed WP17 audit</td>
<td>The read lists are completed; the findings format is word for word the same on WP11 to WP14; the integrator reports <code>INTEGRATED</code>, <code>FINDINGS</code> or <code>BLOCKED</code>; WP00 can be retried; a scout question and a rerun rule cover silent agents; a failed audit is patched like integration findings</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/wbEAWPV\.github\.io\/AFW360_Glance\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 World Bank Group</p>
</div>   
    <div class="nav-footer-center">
<p>AFW 360 data standard · draft v0.3</p>
</div>
    <div class="nav-footer-right">
<p><a href="https://github.com/wbEAWPV/AFW360_Glance">Source</a></p>
</div>
  </div>
</footer>




</body></html>